---


- name: Install NFS packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ nfs_packages }}"

- name: Mount NFS share
  mount:
    fstype: glusterfs
    name: "/mnt2"
    src: "nfs-master:/glusterfs/replica"
    state: mounted
 

#EOF