nexus_user: nexus
nexus_home: /home/nexus
nexus_group: nexus
nexus_version: '3.29.2-02'

nexus_api_usr: 'admin'
nexus_api_psw: 'admin123'
nexus_ip: "{{ansible_eth1.ipv4.address}}"
nexus_path: "{{ nexus_home }}/nexus"
nexus_tcp_ports:
  - 80
  - 5100 #docker registry port
  - 5200 #docker registry port

cache_path: "{{nexus_path}}/cache"
nexus_cache_path: "{{cache_path}}/nexus-ansible-roles"

blobstore_path: /home/nexus/blobstores